.TH BEECAMERAUNSUBSCRIBE 3 "April 27, 1999" "BeeSoft Light" "BeeSoft Light"

.SH NAME
beeCameraUnsubscribe \- unsubscribe to frames captured from cameraServer 

.SH SYNOPSIS
.B #include <bee.h>

.BI "int * beeCameraUnsubscribe(int " numGrabber " ); "

.SH DESCRIPTION
.B "beeCameraUnsubscribe()"
unsubscribes frames from a camera. 

.SH "RETURN VALUE"
On success, the function will return TRUE.  On error, 
.B "beeCameraUnsubscribe()"
will return FALSE.

.SH NOTES
The function hides the details of the message pass among 
BeeSoft Light servers. However, you should at least run 
.BI "tcxServer" ,
.B "colliServer"
and
.B "cameraServer" 
first. Your shell should set environment variable 
.B "TCXHOST" 
to the host name which runs 
.BR "tcxServer". 
You should also invoke function 
.B "beeInitialize()" 
and
.B "beeCameraConnect()"
first in your program. Otherwise, the function will return FALSE.

.SH SEE ALSO
.BR "beeInitialize" (3),
.BR "beeCameraConnect" (3),
.BR "beeCameraSubscribe" (3)


