#include "bee.h"
#include "stdio.h" 
int main() {
    int sleepTime = 4 ;
    float blockLength = 100.0 ;
    beeInitialize() ;
    fprintf(stderr, "\nTranslate 100 centimeter ahead.") ;
    beeTranslateBy(100) ;
    sleep(sleepTime) ;
    fprintf(stderr, "\nTranslate 100 centimeter backward.") ;
    beeTranslateBy(-100) ;
    sleep(sleepTime) ;
    fprintf(stderr, "\nRotate 45 degree clockwise.") ;
    beeRotateBy(45) ;
    sleep(sleepTime) ;
    fprintf(stderr, "\nRotate -90 counterclockwise.") ;
    beeRotateBy(-90) ;
    sleep(sleepTime) ;
    beeSetRotVelocity(30.0) ;
    /* Rotate */
    fprintf(stderr, "\nRotate clockwise.") ;
    beeRotatePositive() ;
    sleep(15) ;
    beeSetRotVelocity(30.0) ;
    fprintf(stderr, "\nRotate counterclockwise") ;
    beeRotateNegative() ;
    sleep(15) ;
    /* Move around a block */
    fprintf(stderr, "\nTRanslate %f centimeter", blockLength) ;
    beeTranslateBy(blockLength) ;
    sleep(sleepTime) ;
    fprintf(stderr, "\nRotate clockwise 90 degree") ;
    beeRotateBy(90) ;
    fprintf(stderr, "\nTRanslate %f centimeter", blockLength) ;
    sleep(sleepTime) ;
    beeTranslateBy(blockLength) ;
    fprintf(stderr, "\nRotate clockwise 90 degree") ;
    sleep(sleepTime) ;
    beeRotateBy(90) ;
    fprintf(stderr, "\nTRanslate %f centimeter", blockLength) ;
    sleep(sleepTime) ;
    beeTranslateBy(blockLength) ;
    fprintf(stderr, "\nRotate clockwise 90 degree") ;
    sleep(sleepTime) ;
    beeRotateBy(90) ;
    fprintf(stderr, "\nTRanslate %f centimeter", blockLength) ;
    sleep(sleepTime) ;
    beeTranslateBy(blockLength) ;
    fprintf(stderr, "\nRotate clockwise 90 degree") ;
    sleep(sleepTime) ;
    beeRotateBy(180) ;
    fprintf(stderr, "\nTRanslate %f centimeter", blockLength) ;
    fprintf(stderr, "\nMove around a block") ;
    sleep(sleepTime) ;
    beeTranslateBy(blockLength) ;
    sleep(sleepTime) ;
    fprintf(stderr, "\nRotate counterclockwise 90 degree") ;
    beeRotateBy(-90) ;
    sleep(sleepTime) ;
    fprintf(stderr, "\nTRanslate %f centimeter", blockLength) ;
    sleep(sleepTime) ;
    beeTranslateBy(blockLength) ;
    sleep(sleepTime) ;
    fprintf(stderr, "\nRotate counterclockwise 90 degree") ;
    beeRotateBy(-90) ;
    sleep(sleepTime) ;
    fprintf(stderr, "\nTRanslate %f centimeter", blockLength) ;
    beeTranslateBy(blockLength) ;
    sleep(sleepTime) ;
    fprintf(stderr, "\nRotate counterclockwise 90 degree") ;
    beeRotateBy(-90) ;
    fprintf(stderr, "\nTRanslate %f centimeter", blockLength) ;
    sleep(sleepTime) ;
    beeTranslateBy(blockLength) ;
    sleep(sleepTime) ;
/*    fprintf(stderr, "\nMake a circle") ;
    beeApproachRelative(-70, 140) ;
    sleep(sleepTime) ;
    beeApproachRelative(121.2, 50) ;
    sleep(sleepTime) ;
    beeApproachRelative(121.2, -50) ;
    sleep(sleepTime) ;
    beeApproachRelative(121.2, 50) ; 
    sleep(sleepTime) ;
    fprintf(stderr, "\nAnother circle") ;
    beeApproachRelative(70, 140) ;
    sleep(sleepTime) ;
    beeApproachRelative(-121.2, 50) ;
    sleep(sleepTime) ;
    beeApproachRelative(-121.2, -50) ;
    sleep(sleepTime) ;
    beeApproachRelative(-121.2, 50) ; 
    sleep(sleepTime) ;
*/    beeSetRotVelocity(30) ;
    sleep(sleepTime) ;
    beeRotatePositive() ;
    beeSetRotVelocity(30.0) ;
    sleep(15) ;
    beeRotateNegative() ;
    sleep(15) ;
    beeStop() ;
    
}
